name: create-branch

on: [workflow_dispatch]

jobs: 
  build:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      with:
        branch: ${{ github.event.inputs.branch }}

  


