name: Super-Linter

on: push

jobs:
  setup-docker:
      runs-on: [self-hosted]
      steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java -cp java HelloWorldApp
          
